# -*- coding: utf-8 -*-
"""AI-481330 : EDA Project II - Retail sales Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SlVJubkYhIHgbbytW_5G1kHmzasiBff4
"""

import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns


st.set_page_config(page_title="Retail Sales EDA", layout="wide")
st.title("Retail Sales Analysis (EDA)")
@st.cache_data

def load_data():
    df = pd.read_csv("Online_Retail.csv",encoding='ISO-8859-1')
    df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
    df = df.dropna(subset=['CustomerID','Description'])
    df['Amount'] = df['Quantity'] * df['UnitPrice']
    return df

df=load_data()
st.subheader("Data Preview")
st.dataframe(df.head())

plt.style.use('ggplot')
st.subheader("Top 10 Countries by Revenue")
country_revenue = (df.groupby('Country')['Amount'].sum().reset_index().sort_values(by='Amount',ascending=False))

fig1,ax1=plt.subplots(figsize=(10,5))
sns.barplot(x='Country', y='Amount', data=country_revenue.head(10),ax=ax1)
ax1.set_title('Top 10 Countries by Revenue')
ax1.tick_params(axis='x', rotation=45)
st.pyplot(fig1)

st.subheader("Top 20 Products by Revenue")
product_revenue = df.groupby('Description')['Amount'].sum().reset_index().sort_values(by='Amount',ascending=False)

fig2,ax2=plt.subplots(figsize=(10,7))
sns.barplot(x='Amount', y='Description', data=product_revenue.head(20),ax=ax2)
ax2.set_title('Top 20 Products by Revenue')
st.pyplot(fig2)

st.subheader("Monthly Sales Trend")
monthly_sales = (df.set_index('InvoiceDate').resample('M')['Amount'].sum().reset_index())
fig3,ax3=plt.subplots(figsize=(15,7))
sns.barplot(x='InvoiceDate', y='Amount', data=monthly_sales,ax=ax3)
ax3.set_title('Monthly Sales Trend')
st.pyplot(fig3)


st.subheader("Top 10 Customers by Revenue")

top_10_customers = (df.groupby('CustomerID')['Amount'].sum().reset_index().sort_values(by='Amount',ascending=False).head(10))
st.dataframe(top_10_customers)

st.subheader("Top 5 Countries Revenue")
top_5_countries = (df.groupby('Country')['Amount'].sum().reset_index().sort_values(by='Amount',ascending=False).head(5))

st.dataframe(top_5_countries)

st.subheader("High Quantity but Low Revenue Products")
product_high_qty_low_revenue = df.groupby('Description')[['Quantity','Amount']].sum().reset_index().sort_values(by=['Quantity','Amount'],ascending=[False,True])

st.dataframe(product_high_qty_low_revenue)

